import i18n from "../components/LangConfig";

let idCounter = 0;

export const ITEMS = [
   {
    id: String(idCounter++),
    imageSrc: "../public/Products/wristwatch.png",
    title: i18n.t("itemsArray.28.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.28.type"),
    details: i18n.t("itemsArray.28.details"),
  },
   {
    id: String(idCounter++),
    imageSrc: "../public/Products/perfume.png",
     title: i18n.t("itemsArray.25.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.25.type"),
    details: i18n.t("itemsArray.25.details"),
  },
   {
    id: String(idCounter++),
    imageSrc: "../public/Products/IPhon.svg",
   title: i18n.t("itemsArray.26.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
  type: i18n.t("itemsArray.26.type"),
    details: i18n.t("itemsArray.26.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/PlayStation.svg',
    title: i18n.t("itemsArray.18.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
   type: i18n.t("itemsArray.18.type"),
    details: i18n.t("itemsArray.18.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/Laptop.svg',
    title: i18n.t("itemsArray.3.title"),
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
     type: i18n.t("itemsArray.3.type"),
   details: i18n.t("itemsArray.3.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/Food.svg',
     title: i18n.t("itemsArray.2.title"),
    price: 100,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
   type: i18n.t("itemsArray.2.type"),
    details: i18n.t("itemsArray.2.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/Gamepad.svg',
    price: 700,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    title: i18n.t("itemsArray.29.title"),
    type: i18n.t("itemsArray.29.type"),
    details: i18n.t("itemsArray.29.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../public/Products/Speakers.svg",
    price: 500,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
  title: i18n.t("itemsArray.27.title"),
    type: i18n.t("itemsArray.27.type"),
    details: i18n.t("itemsArray.27.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../public/Products/Speaker.svg",
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.19.title"),
    type: i18n.t("itemsArray.19.type"),
    details: i18n.t("itemsArray.19.details"),
  },
   {
    id: String(idCounter++),
    imageSrc: "../public/Products/Car.svg",
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.0.title"),
    type: i18n.t("itemsArray.0.type"),
    details: i18n.t("itemsArray.0.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../public/Products/Car2.png",
    price: 3660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title: i18n.t("itemsArray.22.title"),
   type: i18n.t("itemsArray.22.type"),
    details: i18n.t("itemsArray.22.details"),
  },
   {
    id: String(idCounter++),
    imageSrc: "../public/Products/Car3.png",
    price: 2660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title:  i18n.t("itemsArray.23.title"),
       type: i18n.t("itemsArray.23.type"),
    details: i18n.t("itemsArray.23.details"),
  },
   {
    id: String(idCounter++),
    imageSrc: "../public/Products/Car4.png",
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    title:  i18n.t("itemsArray.24.title"),
      type: i18n.t("itemsArray.24.type"),
   details: i18n.t("itemsArray.24.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/chair.svg',
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
title: i18n.t("itemsArray.14.title"),
    type: i18n.t("itemsArray.14.type"),
    details: i18n.t("itemsArray.14.details"),
  },
  // {
  //   id: String(idCounter++),
  //   imageSrc: '../public/Products/Food.svg',
  //   price: 160,
  //   stars: Math.floor(Math.random() * 3) + 3,
  //   rates: Math.floor(Math.random() * 100),
  //   discount: 40,
  //   quantity: 0,
  //   title: "Food",
  //   type: 'General',
  //   // details: i18n.t("itemsArray.8.details"),
  // },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/game.svg',
    price: 1160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
   title: i18n.t("itemsArray.30.title"),
    type: i18n.t("itemsArray.30.type"),
    details: i18n.t("itemsArray.30.details"),
  },
  // {
  //   id: String(idCounter++),
  //   imageSrc: "../public/Products/Gamepad.svg",
  //   price: 360,
  //   stars: Math.floor(Math.random() * 3) + 3,
  //   rates: Math.floor(Math.random() * 100),
  //   discount: 40,
  //   quantity: 0,
  //   title: "Gamepad",
  //   type: 'Gaming',
  //   // details: i18n.t("itemsArray.10.details"),
  // },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/Gucci-duffle-bag.svg',
    price: 160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
      title: i18n.t("itemsArray.9.title"),
    type: i18n.t("itemsArray.9.type"),
    details: i18n.t("itemsArray.9.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/Jacket.svg',
    price: 1160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 35,
    quantity: 0,
   title: i18n.t("itemsArray.6.title"),
    type: i18n.t("itemsArray.6.type"),
    details: i18n.t("itemsArray.6.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/keyboard.svg',
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 30,
    quantity: 0,
       title: i18n.t("itemsArray.11.title"),
    type: i18n.t("itemsArray.11.type"),
    details: i18n.t("itemsArray.11.details"),
  },
  // {
  //   id: String(idCounter++),
  //   imageSrc: '../public/Products/Laptop.svg',
  //   price: 400,
  //   stars: Math.floor(Math.random() * 3) + 3,
  //   rates: Math.floor(Math.random() * 100),
  //   discount: 25,
  //   quantity: 0,
  //   title: "Laptop",
  //   type: 'Technology',
  //   // details: i18n.t("itemsArray.14.details"),
  // },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/monitor.svg',
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
     title: i18n.t("itemsArray.31.title"),
    type: i18n.t("itemsArray.31.type"),
    details: i18n.t("itemsArray.31.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/RGB-liquid-CPU-Cooler.svg',
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
        title: i18n.t("itemsArray.15.title"),
    type: i18n.t("itemsArray.15.type"),
    details: i18n.t("itemsArray.15.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/Set.svg',
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
     title: i18n.t("itemsArray.4.title"),
   type: i18n.t("itemsArray.4.type"),
     details: i18n.t("itemsArray.4.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/Small-BookSelf.svg',
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
   title: i18n.t("itemsArray.7.title"),
    type: i18n.t("itemsArray.7.type"),
    details: i18n.t("itemsArray.7.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/Soccer-Cleats.svg',
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
      title: i18n.t("itemsArray.21.title"),
    type: i18n.t("itemsArray.21.type"),
    details: i18n.t("itemsArray.21.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/The-north-coat.svg',
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
     title: i18n.t("itemsArray.10.title"),
    type: i18n.t("itemsArray.10.type"),
    details: i18n.t("itemsArray.10.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../public/Products/Perfume.svg",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
     title: i18n.t("itemsArray.16.title"),
    type: i18n.t("itemsArray.16.type"),
    details: i18n.t("itemsArray.16.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../public/Products/womenCollections.png",
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
   title: i18n.t("itemsArray.20.title"),
    type: i18n.t("itemsArray.20.type"),
    details: i18n.t("itemsArray.20.details"),
  },
  // {
  //   id: String(idCounter++),
  //   imageSrc: '../public/Products/Speakers.svg',
  //   price: 400,
  //   stars: Math.floor(Math.random() * 3) + 3,
  //   rates: Math.floor(Math.random() * 100),
  //   discount: "",
  //   state: 1,
  //   quantity: 0,
  //   title: "Speakers",
  //   type: 'General',
  //   // details: i18n.t("itemsArray.21.details"),
  // },
  {
    id: String(idCounter++),
    imageSrc: '../public/Products/gameController.png',
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    state: 1,
    quantity: 0,
   title: i18n.t("itemsArray.32.title"),
    type: i18n.t("itemsArray.32.type"),
    details: i18n.t("itemsArray.32.details"),
  },
];