import i18n from "../components/LangConfig";

import wristwatch from "../../assets/Products/wristwatch.png";
import perfume from "../../assets/Products/perfume.png";
import Food from "../../assets/Products/Food.svg";
import Gamepad from "../../assets/Products/Gamepad.svg";
import Speakers from "../../assets/Products/Speakers.svg";
import Speaker from "../../assets/Products/Speaker.svg";
import Car from "../../assets/Products/Car.svg";
import Car2 from "../../assets/Products/Car2.png";
import Car3 from "../../assets/Products/Car3.png";
import Car4 from "../../assets/Products/Car4.png";
import chair from "../../assets/Products/chair.svg";
import game from "../../assets/Products/game.svg";
import gucci from "../../assets/Products/Gucci-duffle-bag.svg";
import Jacket from "../../assets/Products/Jacket.svg";
import keyboard from "../../assets/Products/keyboard.svg";
import monitor from "../../assets/Products/monitor.svg";
import cooler from "../../assets/Products/RGB-liquid-CPU-Cooler.svg";
import Set from "../../assets/Products/Set.svg";
import BookSelf from "../../assets/Products/Small-BookSelf.svg";
import Soccer from "../../assets/Products/Soccer-Cleats.svg";
import Coat from "../../assets/Products/The-north-coat.svg";
import Perfume from "../../assets/Products/Perfume.svg";
import womenCollections from "../../assets/Products/womenCollections.png";
import gameController from "../../assets/Products/gameController.png";
import IPhon from "../../assets/Products/IPhon.svg";
import PlayStation from "../../assets/Products/PlayStation.svg"
import Laptop from  "../../assets/Products/Laptop.svg";

let idCounter = 0;

export const ITEMS = [
  {
    id: String(idCounter++),
    imageSrc: Food,
    title: i18n.t("itemsArray.2.title"),
    price: 100,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.2.type"),
    details: i18n.t("itemsArray.2.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Gamepad,
    title: i18n.t("itemsArray.29.title"),
    price: 700,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.29.type"),
    details: i18n.t("itemsArray.29.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Speakers,
    title: i18n.t("itemsArray.27.title"),
    price: 500,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.27.type"),
    details: i18n.t("itemsArray.27.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Speaker,
    title: i18n.t("itemsArray.19.title"),
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    type: i18n.t("itemsArray.19.type"),
    details: i18n.t("itemsArray.19.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Car,
    title: i18n.t("itemsArray.0.title"),
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    type: i18n.t("itemsArray.0.type"),
    details: i18n.t("itemsArray.0.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Car2,
    title: i18n.t("itemsArray.22.title"),
    price: 3660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    type: i18n.t("itemsArray.22.type"),
    details: i18n.t("itemsArray.22.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Car3,
    title: i18n.t("itemsArray.23.title"),
    price: 2660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    type: i18n.t("itemsArray.23.type"),
    details: i18n.t("itemsArray.23.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Car4,
    title: i18n.t("itemsArray.24.title"),
    price: 660,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    type: i18n.t("itemsArray.24.type"),
    details: i18n.t("itemsArray.24.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: chair,
    title: i18n.t("itemsArray.14.title"),
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    type: i18n.t("itemsArray.14.type"),
    details: i18n.t("itemsArray.14.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: game,
    title: i18n.t("itemsArray.30.title"),
    price: 1160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    type: i18n.t("itemsArray.30.type"),
    details: i18n.t("itemsArray.30.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: gucci,
    title: i18n.t("itemsArray.9.title"),
    price: 160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 40,
    quantity: 0,
    type: i18n.t("itemsArray.9.type"),
    details: i18n.t("itemsArray.9.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Jacket,
    title: i18n.t("itemsArray.6.title"),
    price: 1160,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 35,
    quantity: 0,
    type: i18n.t("itemsArray.6.type"),
    details: i18n.t("itemsArray.6.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: keyboard,
    title: i18n.t("itemsArray.11.title"),
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: 30,
    quantity: 0,
    type: i18n.t("itemsArray.11.type"),
    details: i18n.t("itemsArray.11.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: monitor,
    title: i18n.t("itemsArray.31.title"),
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.31.type"),
    details: i18n.t("itemsArray.31.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: cooler,
    title: i18n.t("itemsArray.15.title"),
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.15.type"),
    details: i18n.t("itemsArray.15.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Set,
    title: i18n.t("itemsArray.4.title"),
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.4.type"),
    details: i18n.t("itemsArray.4.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: BookSelf,
    title: i18n.t("itemsArray.7.title"),
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.7.type"),
    details: i18n.t("itemsArray.7.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Soccer,
    title: i18n.t("itemsArray.21.title"),
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.21.type"),
    details: i18n.t("itemsArray.21.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Coat,
    title: i18n.t("itemsArray.10.title"),
    price: 1200,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.10.type"),
    details: i18n.t("itemsArray.10.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Perfume,
    title: i18n.t("itemsArray.16.title"),
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.16.type"),
    details: i18n.t("itemsArray.16.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: womenCollections,
    title: i18n.t("itemsArray.20.title"),
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.20.type"),
    details: i18n.t("itemsArray.20.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: gameController,
    title: i18n.t("itemsArray.32.title"),
    price: 400,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.32.type"),
    details: i18n.t("itemsArray.32.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: wristwatch,
    title: i18n.t("itemsArray.28.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.28.type"),
    details: i18n.t("itemsArray.28.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: perfume,
    title: i18n.t("itemsArray.25.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.25.type"),
    details: i18n.t("itemsArray.25.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: IPhon,
    title: i18n.t("itemsArray.26.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.26.type"),
    details: i18n.t("itemsArray.26.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: PlayStation,
    title: i18n.t("itemsArray.18.title"),
    price: 960,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.18.type"),
    details: i18n.t("itemsArray.18.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: Laptop,
    title: i18n.t("itemsArray.3.title"),
    price: 360,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.3.type"),
    details: i18n.t("itemsArray.3.details"),
  },

];
